# Site settings
title: FiveYellowMice's Blog
email: hkz85825915@gmail.com
description: >
  我是一位早就不该中二的中二少年，最近又开了一个脑洞，于是就开了这个博客。
baseurl: ""
url: "https://fiveyellowmice.github.io"
timezone: UTC
excerpt_separator: <!--more-->

# Build settings
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
exclude: [Gemfile, Gemfile.lock]
enforce_ssl: fiveyellowmice.github.io
permalink: /posts/:year/:month/:title.html

# Plugins
gems:
  - jemoji
emoji:
  src: "https://fiveyellowmice.tk/static"

# Sass
sass:
  style: compressed

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      excerptable: true
      sitemap: true
      comments: true
      layout: post
  -
    scope:
      path: ""
    values:
      cc_by_sa: true
  -
    scope:
      path: "tags"
    values:
      layout: tag
